//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodorderApp.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFoodSubCat
    {
        public int subcatid { get; set; }
        public string subname { get; set; }
        public string subdesc { get; set; }
        public string subcatimg { get; set; }
        public Nullable<int> catid { get; set; }
        public Nullable<bool> isactive { get; set; }
    }
}
