//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodorderApp.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFood
    {
        public int foodid { get; set; }
        public string food { get; set; }
        public string fooddesc { get; set; }
        public Nullable<int> catid { get; set; }
        public Nullable<int> subcatid { get; set; }
        public string foodimg { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<bool> foodstatus { get; set; }
    }
}
